language: python
dist: xenial
python:
  - 3.6
  - 3.7

install:
  pip install -r requirements-dev.txt

script:
  pytest --flake8 --cov=aiohttp_tal

deploy:
  provider: pypi
  user: "timbaler"
  password:
    secure: "s+UqhkBf1PSxt62EGH67IYNd2iWyKvGwNRJ7xU6PZBROV2Jkc275SEIByDg1n39EzwJloIL9DoxzD2xAvEOlKQsDwL2VT6dj/tsV7Y7Gq7LdSseQjXCTb7M9OCgzxgtmd07U+d3VOFvKi/IFuqWTfDz2QwCYy4Hs1C8zh07lXLIlXTL1gOVatmMmLKLdOkS6JSuxzayZzTZwYtaQTMhihoGQSX5o7QXLycNVMrozQIcsrdiTx5mbO3GCmDUoZhpMlumoogB88Gi7fsqv2tSraloONWBP6A9Q3Z5odSHbGTwfFTnqSoGzOSWwZsrkYHskORgGt71m+W79zFku7nykFLESUee0dq27KQWmB/B1cBpOoDXvms/ODwbI4nxtZ3Dd52OkeAoHYVeOK5XOjCAX9u87KT2dHSuSwmy1pznUidarD/MkcJpC4xtRe/EIesYoePHktIZ9lVmjF6OVIxEsiNBDEMh5hdkdw0Jmc3V95Vl4qM0fK/3kLGZi9hvlAv5A3tHjlKMyo4sTqVpzb0Ntk0yqfvYF2y6qWJzvvIZ3GxINvTJ1dS4SiM0wpD2kHIaCoJGHnNEWrp6FrtaMbng2KzpmP4z+GxNGHxt8AF5DgWHolum2FsIjPxd+Q+MTastwAUUEiEoW2axbsO3QDdDk1lBxNzjNB4G31WOS5kR8rPQ="
  skip_existing: true
  on:
    tags: true
    branch: master
    python: 3.7
